name: Upload JCL to Mainframe

on:
  push:
    paths:
      - 'jcl/*.JCL'
    branches:
      - main

jobs:
  upload-jcl:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zowe CLI
        run: |
          npm install -g @zowe/cli

      - name: Configure Zowe Profile
        run: |
          zowe config init
          zowe profiles create zosmf mainframe-profile \
            --host 204.90.115.200 \
            --port 10443 \
            --user ${{ secrets.MF_USER }} \
            --password ${{ secrets.MF_PASSWORD }} \
            --reject-unauthorized false

      - name: Upload JCL to Mainframe PDS
        run: |
          zowe zos-files upload file-to-data-set "jcl/SAMPLE.JCL" "zxp.public.jcl(SAMPLE)"
